# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK 2.1.500'
  inputs:
    version: 2.1.500	
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
  displayName: 'Run Azure Cosmos DB Emulator container'
- script: dotnet test Toss.Tests\Toss.Tests.csproj  -v n
  displayName: 'Tests'
  env: { 'CosmosDBEndpoint': "$(CosmosDbEmulator.Endpoint)" }  # list of environment variables to add
- script: dotnet test Toss.Tests.E2E\Toss.Tests.E2E.csproj
  displayName: 'E2E Tests'
  env: { 'CosmosDBEndpoint': "$(CosmosDbEmulator.Endpoint)",'CosmosDBKey':"C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==" }  # list of environment variables to add
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')
  inputs:
    testResultsFormat: 'xUnit'

