# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 1.0.4'
  inputs:
    version: 2.1.403
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
  displayName: 'Run Azure Cosmos DB Emulator container'
- script: "echo $(CosmosDbEmulator.Endpoint)"
  displayName: "Print CosmosDB emulator endpoint"
- script: dotnet test
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'xUnit'

