version: '3'

services:
  toss.server:
    image: remibou/toss
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    environment:
      RavenDBEndpoint: "http://ravendb:8080"
    ports:
      - 80:80
  ravendb:
    image: "ravendb/ravendb"
    volumes: 
      - ./Hosting/RavenDB:/root/ravendb
    environment:
      RAVEN_ARGS: "--Setup.Mode=None -c /root/ravendb/settings.json"     
    ports:
      - 8080:8080
    expose:
      - 8080