version: '3.5'
secrets:
  tossserver:
    file: /Users/remibourgarel/.microsoft/usersecrets/ae68635e-649c-4f23-a39b-24a5ea3987f4/secrets.json
services:    
  web:
    image: localhost:5000/toss
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RavenDBEndpoint: "http://ravendb:8080"
    ports:
      - 80:80
    secrets:
      - tossserver
  ravendb:
    image: ravendb/ravendb
    volumes: 
      - ./Hosting/RavenDB:/root/ravendb
    environment:
      RAVEN_ARGS: "--Setup.Mode=None -c /root/ravendb/settings.json"     
    ports:
      - 8080:8080
    expose:
      - 8080