version: '3'
services:
  web:   
    build: 
      context: ..
    restart: always
    ports:
      - "8088:80"
    environment: 
      - GoogleClientId=AAA
      - GoogleClientSecret=AAA
      - MailJetApiKey=
      - MailJetApiSecret=
      - MailJetSender=
      - RavenDBEndpoint=http://ravendb:8080
      - RavenDBDataBase=Tests
      - StripeSecretKey=
      - test=true
  ravendb:
    image: ravendb/ravendb
    ports:
      - 888:8080
  